name: 'Get & Cache Dependecies'
description: 'Get the dependecies (via NPM) and cache them.'
runs:
  using: 'composite' #mora biti composite
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' #cache-hit is defined output of cache@v3
      run: npm ci
      shell: bash #extra setting koji smo dodali kad smo izradili composit action i kad koristimo run key. Kad koristimo drugi action kao npr actions/cache@v3 onda ne moramo dodati shell key
